### ISSUE TITLE
Import on MacOS (x86) fails

### ISSUE THREAD

**Issue by jomade** [ManfredStoiber/stag-python#2]
I installed the library by `pip install stag-python`. It succeeded. 
However, when I try to run, it fails on the import: 
````
>> import stag
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "SOMEPATH/venv/lib/python3.9/site-packages/stag/__init__.py", line 1, in <module>
    from stag._core import *
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(SOMEPATH/venv/lib/python3.9/site-packages/stag/_core.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libopencv_gapi.408.dylib
  Referenced from: <1C1D42C5-A9ED-3D83-9515-0BAABD1FFB37> SOMEPATH/venv/lib/python3.9/site-packages/stag/_core.cpython-39-darwin.so
  Reason: tried: '/private/var/folders/3m/p59k4qdj0f17st0gn2cmj3640000gn/T/cibw-run-er69k1x5/cp39-macosx_x86_64/build/venv/lib/libopencv_gapi.408.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/3m/p59k4qdj0f17st0gn2cmj3640000gn/T/cibw-run-er69k1x5/cp39-macosx_x86_64/build/venv/lib/libopencv_gapi.408.dylib' (no such file), '/private/var/folders/3m/p59k4qdj0f17st0gn2cmj3640000gn/T/cibw-run-er69k1x5/cp39-macosx_x86_64/build/venv/lib/libopencv_gapi.408.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/3m/p59k4qdj0f17st0gn2cmj3640000gn/T/cibw-run-er69k1x5/cp39-macosx_x86_64/build/venv/lib/libopencv_gapi.408.dylib' (no such file), '/usr/local/lib/libopencv_gapi.408.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libopencv_gapi.408.dylib' (no such file), '/usr/local/lib/libopencv_gapi.408.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libopencv_gapi.408.dylib' (no such file)````

I don't really understand what is missing here. I don't have the /private/var/folders/3m folder. Does the library try to look up a directory on the buildserver? (with a rather old version of opencv?)

OpenCV 4.9.0 is installed.

**Comment by ManfredStoiber** [comment]
Hello,

thank you for sharing your issue!
Unfortunately I don't have access to a MacOS machine and therefore can't reproduce the error. Did you already try building the library from source?

Best regards

**Comment by jomade** [comment]
I now tried to build from source and it works. 
Does that help you to fix the build that is distributed via pip?

For reference: For the install, I followed basically the steps that are listed here: https://github.com/ManfredStoiber/stag-python?tab=readme-ov-file#-build-from-source

For Mac this was (using homebrew): 
```
brew install opencv
brew install cmake
brew install ffmpeg
```
I had to add ffmpeg as it started to complain lacking a ffmpeg library ... 

After that, checking out the repository and running `pip install .` which went through.

**Comment by ManfredStoiber** [comment]
Hi again,

thank you for your input, I'm glad it worked when building the package from source.

I now have access to a MacOS machine, although it is based on the arm64 architecture. Using the latest version (v1.1.0), everything works as expected on my end. I would appreciate it if you could try installing the package via pip again to confirm if the issue is now resolved.

Thank you very much!

Kind regards

**Comment by jomade** [comment]
I can confirm that the issue is resolved with the new version. It could be installed from pip and then run without issues. 
Thanks for the resolution!

**Comment by ManfredStoiber** [comment]
Thank you very much for your contribution!
